# Generated by Django 6.0 on 2025-12-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('marmitas', 'Marmitas'), ('bebidas', 'Bebidas'), ('sobremesas', 'Sobremesas'), ('acompanhamentos', 'Acompanhamentos'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
    ]
